// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreinamentoWebAPI.Data;

#nullable disable

namespace TreinamentoWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230513151054_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TreinamentoWebAPI.Domain.Poder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Habilidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("habilidade");

                    b.HasKey("Id");

                    b.HasIndex("Habilidade")
                        .IsUnique();

                    b.ToTable("poder", (string)null);
                });

            modelBuilder.Entity("TreinamentoWebAPI.Domain.SuperHeroi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataAparicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_aparicao");

                    b.Property<string>("IdentidadeSecreta")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("identidade_secreta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nome");

                    b.Property<int?>("PoderId")
                        .HasColumnType("int")
                        .HasColumnName("poder_id");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("PoderId");

                    b.ToTable("super_heroi", (string)null);
                });

            modelBuilder.Entity("TreinamentoWebAPI.Domain.SuperHeroi", b =>
                {
                    b.HasOne("TreinamentoWebAPI.Domain.Poder", "Poder")
                        .WithMany("SuperHerois")
                        .HasForeignKey("PoderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Poder");
                });

            modelBuilder.Entity("TreinamentoWebAPI.Domain.Poder", b =>
                {
                    b.Navigation("SuperHerois");
                });
#pragma warning restore 612, 618
        }
    }
}
